### ISSUE TITLE
DONT TRUST THIS BROWSER

### ISSUE THREAD

**Issue by DatEmage** [SLT-World/SLBr#2]
ITS AN TROJAN INJECTOR, don't believe me, scan it on virustotal urself

**Comment by SLT-World** [comment]
https://www.virustotal.com/gui/file/4345ee2ebf1bafccab0ace236044f8ce972512155840bcec247adeec2c480001

Cylance's Unsafe means the publisher is not verified
Zillya's Trojan.DllInject.Win32.16662 was mentioning the modification of the HKey to add browser to the default browser list

**Comment by SLT-World** [comment]
Update 2022.6.25.0
https://www.virustotal.com/gui/file/d6d7d557c4e6e1da6e903bfc0b6dd60a88a83645af3bd328a48a382e299c72cb?nocache=1
Only 1 engine detected version 2022.6.25.0 as unsafe.
